name: Doxygen → Pages
on:
  push: { branches: [ main ] }
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # allows push to gh-pages

    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: Doxyfile     # or path/to/your file
          folder: DoxyGen           # <── PUBLISH **THIS** FOLDER
          branch: gh-pages          # Pages branch
