name: Publish static HTML
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  pages: write        # allow deployment
  id-token: write     # OIDC auth

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Create .nojekyll so folders with '_' work
      - run: touch .nojekyll

      - uses: actions/upload-pages-artifact@v3     # bundle everything
        with:
          path: .

      - uses: actions/deploy-pages@v4              # push to Pages
